gperf.diff: simplify to fix yet another new build failure
a new build error involving the gperf generated comparison function
popped up, this time due to missing linkage of the supposedly inlined
function:

> cp/except.o: In function `nothrow_libfn_p(tree_node const*)':
> except.c:(.text+0x1d94): undefined reference to `libc_name_p(char const*, unsigned int)'
> collect2: error: ld returned 1 exit status

closes #82